import type { ComponentRecord } from "./types";

// Representative values near ambient temperature. Physical properties vary
// with temperature, purity and supplier; the UI keeps this limitation visible.
export const electrolyteComponents: ComponentRecord[] = [
  {
    id: "ec",
    name: "Ethylene carbonate",
    aliases: ["EC", "1,3-dioxolan-2-one"],
    role: "solvent",
    family: "Cyclic carbonate",
    formula: "C3H4O3",
    smiles: "O=C1OCCO1",
    molarMass: 88.06,
    density: 1.32,
    dielectric: 89.8,
    boilingPoint: 248,
    notes: "High-permittivity cyclic carbonate; solid near room temperature.",
  },
  {
    id: "pc",
    name: "Propylene carbonate",
    aliases: ["PC", "4-methyl-1,3-dioxolan-2-one"],
    role: "solvent",
    family: "Cyclic carbonate",
    formula: "C4H6O3",
    smiles: "CC1COC(=O)O1",
    molarMass: 102.09,
    density: 1.2,
    dielectric: 64.9,
    viscosity: 2.5,
    boilingPoint: 242,
    notes: "Polar aprotic solvent with a wide liquid range.",
  },
  {
    id: "dmc",
    name: "Dimethyl carbonate",
    aliases: ["DMC"],
    role: "solvent",
    family: "Linear carbonate",
    formula: "C3H6O3",
    smiles: "COC(=O)OC",
    molarMass: 90.08,
    density: 1.07,
    dielectric: 3.1,
    viscosity: 0.59,
    boilingPoint: 90,
    flashPoint: 18,
    notes: "Low-viscosity linear carbonate; flammable.",
  },
  {
    id: "emc",
    name: "Ethyl methyl carbonate",
    aliases: ["EMC"],
    role: "solvent",
    family: "Linear carbonate",
    formula: "C4H8O3",
    smiles: "CCOC(=O)OC",
    molarMass: 104.11,
    density: 1.01,
    dielectric: 3,
    viscosity: 0.65,
    boilingPoint: 107,
    notes: "Low-viscosity carbonate widely used in mixed electrolytes.",
  },
  {
    id: "dec",
    name: "Diethyl carbonate",
    aliases: ["DEC"],
    role: "solvent",
    family: "Linear carbonate",
    formula: "C5H10O3",
    smiles: "CCOC(=O)OCC",
    molarMass: 118.13,
    density: 0.97,
    dielectric: 2.8,
    viscosity: 0.75,
    boilingPoint: 126,
    notes: "Low-polarity linear carbonate used to lower viscosity.",
  },
  {
    id: "fec",
    name: "Fluoroethylene carbonate",
    aliases: ["FEC"],
    role: "additive",
    family: "Fluorinated carbonate",
    formula: "C3H3FO3",
    smiles: "O=C1OC(F)CO1",
    molarMass: 106.05,
    density: 1.45,
    notes: "Film-forming additive frequently used for Si and Li-metal interfaces.",
  },
  {
    id: "vc",
    name: "Vinylene carbonate",
    aliases: ["VC", "1,3-dioxol-2-one"],
    role: "additive",
    family: "Unsaturated carbonate",
    formula: "C3H2O3",
    smiles: "O=C1OC=CO1",
    molarMass: 86.05,
    density: 1.36,
    notes: "Common SEI-forming additive; concentration is formulation dependent.",
  },
  {
    id: "dme",
    name: "1,2-Dimethoxyethane",
    aliases: ["DME", "glyme"],
    role: "solvent",
    family: "Ether",
    formula: "C4H10O2",
    smiles: "COCCOC",
    molarMass: 90.12,
    density: 0.87,
    dielectric: 7.2,
    viscosity: 0.46,
    boilingPoint: 85,
    notes: "Chelating ether solvent common in Li-metal and sulfur systems.",
  },
  {
    id: "diglyme",
    name: "Diethylene glycol dimethyl ether",
    aliases: ["Diglyme", "G2", "2-glyme"],
    role: "solvent",
    family: "Glyme ether",
    formula: "C6H14O3",
    smiles: "COCCOCCOC",
    molarMass: 134.18,
    density: 0.94,
    viscosity: 1,
    boilingPoint: 162,
    notes: "Multidentate ether with stronger Li-ion coordination than DME.",
  },
  {
    id: "dol",
    name: "1,3-Dioxolane",
    aliases: ["DOL"],
    role: "solvent",
    family: "Cyclic ether",
    formula: "C3H6O2",
    smiles: "C1COCO1",
    molarMass: 74.08,
    density: 1.06,
    dielectric: 7.1,
    viscosity: 0.6,
    boilingPoint: 75,
    notes: "Cyclic ether often paired with DME in sulfur electrolytes.",
  },
  {
    id: "acn",
    name: "Acetonitrile",
    aliases: ["ACN", "AN"],
    role: "solvent",
    family: "Nitrile",
    formula: "C2H3N",
    smiles: "CC#N",
    molarMass: 41.05,
    density: 0.79,
    dielectric: 35.9,
    viscosity: 0.34,
    boilingPoint: 82,
    flashPoint: 2,
    notes: "Very low-viscosity polar solvent; volatile and flammable.",
  },
  {
    id: "dmso",
    name: "Dimethyl sulfoxide",
    aliases: ["DMSO"],
    role: "solvent",
    family: "Sulfoxide",
    formula: "C2H6OS",
    smiles: "CS(=O)C",
    molarMass: 78.13,
    density: 1.1,
    dielectric: 46.7,
    viscosity: 2,
    boilingPoint: 189,
    notes: "Strong donor solvent with high polarity.",
  },
  {
    id: "sulfolane",
    name: "Sulfolane",
    aliases: ["TMS", "tetramethylene sulfone"],
    role: "solvent",
    family: "Sulfone",
    formula: "C4H8O2S",
    smiles: "O=S1(=O)CCCC1",
    molarMass: 120.17,
    density: 1.26,
    dielectric: 43,
    viscosity: 10.3,
    boilingPoint: 285,
    notes: "High-polarity, low-volatility sulfone with comparatively high viscosity.",
  },
  {
    id: "tte",
    name: "1,1,2,2-Tetrafluoroethyl 2,2,3,3-tetrafluoropropyl ether",
    aliases: ["TTE"],
    role: "diluent",
    family: "Fluorinated ether",
    formula: "C5H4F8O",
    smiles: "FC(F)(F)C(F)OCC(F)(F)C(F)F",
    molarMass: 232.09,
    notes: "Weakly coordinating fluorinated diluent used in localized high-concentration formulations.",
  },
  {
    id: "lifsi",
    name: "Lithium bis(fluorosulfonyl)imide",
    aliases: ["LiFSI"],
    role: "salt",
    family: "Sulfonylimide salt",
    formula: "LiN(SO2F)2",
    smiles: "[Li+].[N-](S(=O)(=O)F)S(=O)(=O)F",
    molarMass: 187.07,
    notes: "Highly dissociating lithium salt; interfacial and corrosion behavior depend on formulation.",
  },
  {
    id: "litfsi",
    name: "Lithium bis(trifluoromethanesulfonyl)imide",
    aliases: ["LiTFSI"],
    role: "salt",
    family: "Sulfonylimide salt",
    formula: "LiN(SO2CF3)2",
    smiles: "[Li+].[N-](S(=O)(=O)C(F)(F)F)S(=O)(=O)C(F)(F)F",
    molarMass: 287.09,
    notes: "Thermally robust salt widely used in ethers, ionic liquids and polymers.",
  },
  {
    id: "lipf6",
    name: "Lithium hexafluorophosphate",
    aliases: ["LiPF6"],
    role: "salt",
    family: "Fluorophosphate salt",
    formula: "LiPF6",
    smiles: "[Li+].F[P-](F)(F)(F)(F)F",
    molarMass: 151.91,
    notes: "Commercial carbonate-electrolyte salt; moisture sensitive.",
  },
  {
    id: "libf4",
    name: "Lithium tetrafluoroborate",
    aliases: ["LiBF4"],
    role: "salt",
    family: "Fluoroborate salt",
    formula: "LiBF4",
    smiles: "[Li+].F[B-](F)(F)F",
    molarMass: 93.75,
    notes: "Lithium salt with useful thermal stability and moderate conductivity.",
  },
  {
    id: "libob",
    name: "Lithium bis(oxalato)borate",
    aliases: ["LiBOB"],
    role: "salt",
    family: "Borate salt",
    formula: "LiB(C2O4)2",
    smiles: "[Li+].O=C1O[B-]2(OC1=O)OC(=O)C(=O)O2",
    molarMass: 193.79,
    notes: "Borate salt/additive associated with protective interphase formation.",
  },
  {
    id: "lino3",
    name: "Lithium nitrate",
    aliases: ["LiNO3"],
    role: "additive",
    family: "Inorganic salt",
    formula: "LiNO3",
    smiles: "[Li+].[O-][N+](=O)[O-]",
    molarMass: 68.95,
    notes: "Common additive for regulating lithium-metal interfaces, especially in ether systems.",
  },
];

export const componentByAlias = new Map(
  electrolyteComponents.flatMap((component) =>
    [component.name, ...component.aliases].map((alias) => [
      alias.toLowerCase(),
      component,
    ] as const),
  ),
);

