import { writeFile } from "node:fs/promises";
import countries from "world-countries";

const regions = countries
  .filter(
    (country) =>
      country.status === "officially-assigned" &&
      /^[A-Z]{2}$/.test(country.cca2) &&
      country.latlng.length === 2,
  )
  .map((country) => ({
    code: country.cca2,
    name: country.name.common,
    coordinates: [country.latlng[1], country.latlng[0]],
  }))
  .sort((left, right) => left.name.localeCompare(right.name));

const output = `// Generated by tools/export_reach_regions.mjs.\nexport const reachRegionsData = ${JSON.stringify(regions)} as const;\n`;
await writeFile(new URL("../src/reach-regions.ts", import.meta.url), output);
console.log(`Exported ${regions.length} ISO regions.`);
